jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: github.request('PUT /repos/${{github.repository}}/actions/workflows/workflow.yml/enable')
      - uses: actions/checkout@v2
      - name: step
        run: docker build --pull --force-rm .

name: workflow

'on':
  pull_request:
    branches: [master]
  push:
    branches: [master]
  schedule:
    # generated randomly
    - cron: '44 18 * * SUN'
